---
name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Lint Markdown files
        uses: actionsx/prettier@v2
        with:
          args: --check '**/*.md'

      - name: Lint JSON files
        uses: actionsx/prettier@v2
        with:
          args: --check '**/*.json'
